export const conceptImages = {
  heroTea: {
    src: "https://images.pexels.com/photos/27848203/pexels-photo-27848203.jpeg?cs=srgb&dl=pexels-yohantha-gunawarna-1265127381-27848203.jpg&fm=jpg",
    alt: "Misty tea estate hills in Kandy, Sri Lanka at sunrise",
    credit: "Yohantha Gunawarna / Pexels",
    source: "https://www.pexels.com/photo/the-morning-mist-weaves-through-kandy-s-tea-estate-as-the-sun-kisses-the-rolling-hills-awake-27848203/",
  },
  hillLake: {
    src: "https://images.pexels.com/photos/35637980/pexels-photo-35637980.jpeg?cs=srgb&dl=pexels-shafky-zubair-2158030401-35637980.jpg&fm=jpg",
    alt: "Serene lake and green hills in Sri Lanka",
    credit: "Shafky Zubair / Pexels",
    source: "https://www.pexels.com/photo/serene-lake-and-verdant-hills-in-sri-lanka-35637980/",
  },
  kandyCity: {
    src: "https://images.pexels.com/photos/739409/pexels-photo-739409.jpeg?cs=srgb&dl=pexels-eugene-dorosh-230277-739409.jpg&fm=jpg",
    alt: "Kandy city and lake surrounded by green hills in Sri Lanka",
    credit: "Eugene Dorosh / Pexels",
    source: "https://www.pexels.com/photo/aerial-view-of-the-city-739409/",
  },
  roomPanoramic: {
    src: "https://images.pexels.com/photos/28347470/pexels-photo-28347470.jpeg?cs=srgb&dl=pexels-svh-manali-1801124329-28347470.jpg&fm=jpg",
    alt: "Premium mountain-view hotel bedroom with warm timber finishes",
    credit: "SVH Manali / Pexels",
    source: "https://www.pexels.com/photo/a-hotel-room-with-wooden-floors-and-a-large-bed-28347470/",
  },
  roomNature: {
    src: "https://images.pexels.com/photos/28347472/pexels-photo-28347472.jpeg?cs=srgb&dl=pexels-svh-manali-1801124329-28347472.jpg&fm=jpg",
    alt: "Bright premium hotel room with large windows and mountain views",
    credit: "SVH Manali / Pexels",
    source: "https://www.pexels.com/photo/a-hotel-room-with-a-desk-and-a-window-28347477/",
  },
  roomLake: {
    src: "https://images.pexels.com/photos/28347473/pexels-photo-28347473.jpeg?cs=srgb&dl=pexels-svh-manali-1801124329-28347473.jpg&fm=jpg",
    alt: "Elegant hotel bedroom facing a mountain-view balcony",
    credit: "SVH Manali / Pexels",
    source: "https://www.pexels.com/photo/a-hotel-room-with-a-desk-and-a-window-28347477/",
  },
  dining: {
    src: "https://images.pexels.com/photos/6466281/pexels-photo-6466281.jpeg?cs=srgb&dl=pexels-cottonbro-6466281.jpg&fm=jpg",
    alt: "Elegant hotel breakfast with pastries, fruit and fresh juice",
    credit: "cottonbro studio / Pexels",
    source: "https://www.pexels.com/photo/breakfast-table-setting-in-a-hotel-room-6466281/",
  },
  breakfastTerrace: {
    src: "https://images.pexels.com/photos/4993247/pexels-photo-4993247.jpeg?cs=srgb&dl=pexels-rachel-claire-4993247.jpg&fm=jpg",
    alt: "Tropical resort breakfast set beside an open view",
    credit: "Rachel Claire / Pexels",
    source: "https://www.pexels.com/photo/served-tables-on-terrace-in-tropical-resort-4993247/",
  },,
  roomSriLanka: {
    src: "https://images.pexels.com/photos/34803620/pexels-photo-34803620.jpeg?cs=srgb&dl=pexels-hiruna-wanninayake-2156204267-34803620.jpg&fm=jpg",
    alt: "Elegant Sri Lankan hotel room with warm wooden furniture and natural light",
    credit: "Hiruna Wanninayake / Pexels",
    source: "https://www.pexels.com/photo/luxurious-sri-lankan-hotel-room-interior-34803620/",
  },
  roomCozyMountain: {
    src: "https://images.pexels.com/photos/30769149/pexels-photo-30769149/free-photo-of-cozy-hotel-room-with-scenic-mountain-view.jpeg?auto=compress&cs=tinysrgb&w=2400",
    alt: "Cozy hotel room with a scenic mountain view and natural light",
    credit: "Petra Nesti / Pexels",
    source: "https://www.pexels.com/photo/cozy-hotel-room-with-scenic-mountain-view-30769149/",
  },
  roomModernView: {
    src: "https://images.pexels.com/photos/30722813/pexels-photo-30722813/free-photo-of-modern-hotel-room-with-scenic-view.jpeg?auto=compress&cs=tinysrgb&w=2400",
    alt: "Modern hotel room with large windows and a scenic mountain view",
    credit: "mohd hasan / Pexels",
    source: "https://www.pexels.com/photo/modern-hotel-room-with-scenic-view-30722813/",
  },
  roomBathView: {
    src: "https://images.pexels.com/photos/26859068/pexels-photo-26859068/free-photo-of-bedroom-with-bathtub.jpeg?auto=compress&cs=tinysrgb&w=2400",
    alt: "Spacious hotel bedroom with bathtub and mountain view",
    credit: "Ahmet ÇÖTÜR / Pexels",
    source: "https://www.pexels.com/photo/bedroom-with-bathtub-26859068/",
  },
  diningService: {
    src: "https://images.pexels.com/photos/6466284/pexels-photo-6466284.jpeg?auto=compress&cs=tinysrgb&w=2400",
    alt: "Elegant hotel room service breakfast with pastries and fresh juice",
    credit: "cottonbro studio / Pexels",
    source: "https://www.pexels.com/photo/person-checking-order-from-hotel-room-service-6466284/",
  },
  diningPoached: {
    src: "https://images.pexels.com/photos/6466291/pexels-photo-6466291.jpeg?auto=compress&cs=tinysrgb&w=2400",
    alt: "Luxury hotel breakfast with poached eggs, pastries and orange juice",
    credit: "cottonbro studio / Pexels",
    source: "https://www.pexels.com/photo/toast-with-poached-egg-6466291/",
  },
  diningSpread: {
    src: "https://images.pexels.com/photos/36782826/pexels-photo-36782826.jpeg?auto=compress&cs=tinysrgb&w=2400",
    alt: "Luxurious hotel breakfast spread with fruit, pastries and plated dishes",
    credit: "Misbaa eri / Pexels",
    source: "https://www.pexels.com/photo/luxurious-hotel-breakfast-spread-with-variety-36782826/",
  },
  kandyTemple: {
    src: "https://images.pexels.com/photos/33404364/pexels-photo-33404364.jpeg?auto=compress&cs=tinysrgb&w=2400",
    alt: "Temple of the Tooth in Kandy, Sri Lanka under a clear sky",
    credit: "Ruwan Lakmal / Pexels",
    source: "https://www.pexels.com/photo/temple-of-the-tooth-in-kandy-sri-lanka-33404364/",
  },
  kandyHillside: {
    src: "https://images.pexels.com/photos/32861262/pexels-photo-32861262.jpeg?auto=compress&cs=tinysrgb&w=2400",
    alt: "Scenic hillside view of Kandy city and surrounding greenery",
    credit: "Shifna Captures / Pexels",
    source: "https://www.pexels.com/photo/scenic-hillside-view-of-kandy-city-sri-lanka-32861262/",
  },
  kandyLake: {
    src: "https://images.pexels.com/photos/36369846/pexels-photo-36369846.jpeg?auto=compress&cs=tinysrgb&w=2400",
    alt: "Tranquil Kandy lake scene with an island pavilion and tropical greenery",
    credit: "Charitha Vimukthi / Pexels",
    source: "https://www.pexels.com/photo/tranquil-lakeside-view-with-island-pavilion-36369846/",
  },
} as const;
